POST https://reminder-primo-b01b21f4b5c9.herokuapp.com/api/sendSMS HTTP/1.1
content-type: application/json

{
    "fechaInicio": "2023-08-08 08:50:00",
    "celular": "573185274636",
    "mensaje": "Probando a ver si envia mensajes"
}